##########################################################################################
# vicar/__init__.pyi
##########################################################################################
"""Type stub for the vicar package.

The `src` tree carries no inline annotations, so type information for the public symbols
is published here instead. Every public class is described in this one file, because the
only supported import is ``from vicar import ...``; the submodules that define the
classes are an implementation detail and carry no stubs of their own. The stub describes
the shape of the API exactly: every public name, its parameters, which of them are
keyword-only, and which have defaults. Types are taken from the docstrings, so a change to
a documented type belongs in both places.
"""

import re
from collections.abc import Iterator, Sequence
from pathlib import Path
from typing import IO, Any, ClassVar, TypeAlias

from filecache import FCPath
from numpy.typing import ArrayLike, NDArray

__version__: str

__all__ = ['VicarError', 'VicarImage', 'VicarLabel']

# A key selecting one label parameter: an index, a name, (name, occurrence),
# (name, after), or (name, after, value).
_Key: TypeAlias = (int | str | tuple[str, int] | tuple[str, str]
                   | tuple[str, str, Any])

# The key of a parameter in iteration order: its name if unique, else (name, occurrence).
_UniqueKey: TypeAlias = str | tuple[str, int]

# A label parameter value.
_Value: TypeAlias = int | float | str | list[Any]

_PathLike: TypeAlias = FCPath | Path | str
_Pattern: TypeAlias = str | re.Pattern[str]

# Label content accepted by VicarLabel.insert().
_Content: TypeAlias = (IO[Any] | _PathLike | dict[str, Any] | list[Any]
                       | tuple[Any, ...])

class VicarError(ValueError): ...

class VicarLabel:
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __init__(self, source: IO[Any] | _PathLike | dict[str, Any] | list[Any]
                 | None = ..., strict: bool = ...) -> None: ...
    @property
    def filepath(self) -> FCPath | None: ...
    @filepath.setter
    def filepath(self, value: _PathLike | None) -> None: ...
    def copy(self) -> VicarLabel: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def append(self, source: _Content | None) -> None: ...
    def insert(self, source: _Content, indx: int) -> None: ...
    def reorder(self, *keys: _Key) -> None: ...
    def arg(self, key: _Key, value: int | float | str | None = ...
            ) -> int | list[int]: ...
    def __getitem__(self, key: _Key) -> _Value: ...
    def get(self, key: _Key, default: _Value) -> _Value: ...
    def __setitem__(self, key: _Key, value: _Value | tuple[Any, ...]) -> None: ...
    def __delitem__(self, key: _Key) -> None: ...
    def __contains__(self, key: _Key) -> bool: ...
    def value_str(self, key: _Key) -> str: ...
    def name_value_str(self, key: _Key, pad: bool = ...) -> str: ...
    def export(self, resize: bool = ...) -> tuple[str, str]: ...
    def as_string(self, start: _Key = ..., stop: _Key | None = ..., sep: str = ...
                  ) -> str: ...
    def __iter__(self) -> Iterator[_UniqueKey]: ...
    def __next__(self) -> _UniqueKey: ...
    def names(self, pattern: _Pattern | None = ...) -> list[str]: ...
    def keys(self, pattern: _Pattern | None = ...) -> list[_UniqueKey]: ...
    def values(self, pattern: _Pattern | None = ...) -> list[_Value]: ...
    def items(self, pattern: _Pattern | None = ..., unique: bool = ...
              ) -> list[tuple[_UniqueKey, _Value]]: ...
    def args(self, pattern: _Pattern | None = ...) -> Sequence[int]: ...
    @staticmethod
    def read_label(source: _PathLike | IO[Any], _extra: bool = ...
                   ) -> str | tuple[str, bytes]: ...
    @staticmethod
    def from_file(filepath: _PathLike) -> VicarLabel: ...
    def write_label(self, filepath: _PathLike | None = ...) -> None: ...
    @staticmethod
    def is_vicar_file(filepath: _PathLike) -> bool: ...

class VicarImage:
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __init__(self, source: _PathLike | VicarLabel | None = ...,
                 array: ArrayLike | None = ..., *, prefix: ArrayLike | None = ...,
                 binheader: ArrayLike | bytes | None = ..., strict: bool = ...
                 ) -> None: ...
    @property
    def filepath(self) -> FCPath | None: ...
    @filepath.setter
    def filepath(self, value: _PathLike | None) -> None: ...
    @property
    def label(self) -> VicarLabel: ...
    @property
    def array2d(self) -> NDArray[Any] | None: ...
    @property
    def data_2d(self) -> NDArray[Any] | None: ...
    @property
    def array3d(self) -> NDArray[Any] | None: ...
    @property
    def data_3d(self) -> NDArray[Any] | None: ...
    @property
    def array(self) -> NDArray[Any] | None: ...
    @array.setter
    def array(self, value: ArrayLike | None) -> None: ...
    @property
    def prefix2d(self) -> NDArray[Any]: ...
    @property
    def prefix_2d(self) -> NDArray[Any]: ...
    @property
    def prefix3d(self) -> NDArray[Any]: ...
    @property
    def prefix_3d(self) -> NDArray[Any]: ...
    @property
    def prefix(self) -> NDArray[Any]: ...
    @prefix.setter
    def prefix(self, value: ArrayLike | None) -> None: ...
    @property
    def binheader(self) -> NDArray[Any] | bytes | None: ...
    @binheader.setter
    def binheader(self, value: NDArray[Any] | bytes | None) -> None: ...
    def copy(self) -> VicarImage: ...
    def deepcopy(self) -> VicarImage: ...
    def __eq__(self, other: object) -> bool: ...
    @staticmethod
    def from_file(filepath: _PathLike, extraneous: str = ..., strict: bool = ...
                  ) -> VicarImage | tuple[VicarImage, bytes | None]: ...
    @staticmethod
    def from_array(array: ArrayLike, strict: bool = ...) -> VicarImage: ...
    def write_file(self, filepath: _PathLike | None = ...) -> None: ...
    def binheader_array(self, kind: str = ..., size: int | None = ...
                        ) -> NDArray[Any] | None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: _Key) -> _Value: ...
    def get(self, key: _Key, default: _Value) -> _Value: ...
    def __setitem__(self, key: _Key, value: _Value | tuple[Any, ...]) -> None: ...
    def __delitem__(self, key: _Key) -> None: ...
    def __contains__(self, key: _Key) -> bool: ...
    def arg(self, key: _Key) -> int | list[int]: ...
    def __iter__(self) -> Iterator[_UniqueKey]: ...
    def names(self, pattern: _Pattern | None = ...) -> list[str]: ...
    def keys(self, pattern: _Pattern | None = ...) -> list[_UniqueKey]: ...
    def values(self, pattern: _Pattern | None = ...) -> list[_Value]: ...
    def items(self, pattern: _Pattern | None = ..., unique: bool = ...
              ) -> list[tuple[_UniqueKey, _Value]]: ...
    def args(self, pattern: _Pattern | None = ...) -> Sequence[int]: ...
    def as_dict(self) -> VicarLabel: ...
